//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditDetail
    {
        public CreditDetail()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int Id { get; set; }
        public string CreditNumber { get; set; }
        public Nullable<System.DateTime> Validity { get; set; }
        public string BackDigits { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
    }
}
