//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Attendances = new HashSet<Attendance>();
            this.Payments = new HashSet<Payment>();
            this.StudentInLessons = new HashSet<StudentInLesson>();
            this.StudentInSubscriptions = new HashSet<StudentInSubscription>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string IdentityNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string Pignicher { get; set; }
        public string StudentKind { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<int> CreditDetailsId { get; set; }
    
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual CreditDetail CreditDetail { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<StudentInLesson> StudentInLessons { get; set; }
        public virtual ICollection<StudentInSubscription> StudentInSubscriptions { get; set; }
    }
}
