//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public Subscription()
        {
            this.StudentInSubscriptions = new HashSet<StudentInSubscription>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> WeeksNum { get; set; }
        public Nullable<int> DaysInWeekNum { get; set; }
    
        public virtual ICollection<StudentInSubscription> StudentInSubscriptions { get; set; }
    }
}
